AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Parameters:
    # No-op section removed
    AppName:
        Type: String
        Default: "dx-aws-pipeline-badges"
Resources:
    LambdaZipsBucket:
        Type: AWS::S3::Bucket

    # Log Groups
    StatusBadgeLogGroup:
        Type: "AWS::Logs::LogGroup"
        Properties:
            LogGroupName: !Sub "/aws/lambda/${AppName}-status"
    CommitIdBadgeLogGroup:
        Type: "AWS::Logs::LogGroup"
        Properties:
            LogGroupName: !Sub "/aws/lambda/${AppName}-commit-id"

    # Roles
    IamRoleLambdaExecution:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - "sts:AssumeRole"
            Policies:
                - PolicyName: !Sub "${AppName}-lambda-policy"
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogStream"
                            Resource:
                                - !Sub >-
                                    arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AppName}*:*
                          - Effect: Allow
                            Action:
                                - "logs:PutLogEvents"
                            Resource:
                                - !Sub >-
                                    arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AppName}*:*:*
                          - Effect: Allow
                            Action:
                                - "s3:PutObject"
                                - "s3:PutObjectAcl"
                            Resource: !Sub "arn:aws:s3:::${AppName}-images/*"
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                            Resource: "arn:aws:logs:*:*:*"
            Path: /
            RoleName: !Join
                - "-"
                - - !Sub "${AppName}-lambda-role"
                  - !Ref "AWS::Region"

    CommitIdFunctionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Policies:
                - PolicyName: CommitIdFunctionRolePolicy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                            Resource:
                                - "arn:aws:logs:*:*:*"
                          - Effect: Allow
                            Action:
                                - "codepipeline:GetPipelineExecution"
                                - "codepipeline:ListActionExecutions"
                            Resource:
                                - "*"
                          - Effect: Allow
                            Action:
                                - "s3:PutObject"
                                - "s3:PutObjectAcl"
                            Resource: !Sub "arn:aws:s3:::${AppName}-images/*"

    # Functions
    StatusBadgeLambdaFunction:
        DependsOn:
            - CopyZips
            - StatusBadgeLogGroup
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Ref "LambdaZipsBucket"
                S3Key: dist_status_badges.zip
            FunctionName: !Sub "${AppName}-status"
            Handler: index.handler
            MemorySize: 192
            Role: !GetAtt
                - IamRoleLambdaExecution
                - Arn
            Runtime: nodejs20.x
            Timeout: 6
            Environment:
                Variables:
                    BUCKET_BADGES: !Sub "${AppName}-images"

    CommitIdBadgeLambdaFunction:
        DependsOn:
            - CopyZips
            - CommitIdBadgeLogGroup
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Ref "LambdaZipsBucket"
                S3Key: dist_commit_badges.zip
            FunctionName: !Sub "${AppName}-commit-id"
            Handler: index.handler
            MemorySize: 192
            Role: !GetAtt
                - CommitIdFunctionRole
                - Arn
            Runtime: nodejs20.x
            Timeout: 6
            Environment:
                Variables:
                    BUCKET_BADGES: !Sub "${AppName}-images"

    # CloudWatch Events
    StatusBadgeEventsRuleCloudWatchEvent1:
        Type: "AWS::Events::Rule"
        Properties:
            EventPattern:
                source:
                    - aws.codebuild
                detail-type:
                    - CodeBuild Build State Change
            State: ENABLED
            Description: Triggered upon status change of CodeBuild project
            Name: !Sub "${AppName}-status-build-event"
            Targets:
                - Arn: !GetAtt
                      - StatusBadgeLambdaFunction
                      - Arn
                  Id: statusBadgeCloudWatchEvent
    StatusBadgeLambdaPermissionEventsRuleCloudWatchEvent1:
        Type: "AWS::Lambda::Permission"
        Properties:
            FunctionName: !GetAtt
                - StatusBadgeLambdaFunction
                - Arn
            Action: "lambda:InvokeFunction"
            Principal: events.amazonaws.com
            SourceArn: !GetAtt
                - StatusBadgeEventsRuleCloudWatchEvent1
                - Arn
    StatusBadgeEventsRuleCloudWatchEvent2:
        Type: "AWS::Events::Rule"
        Properties:
            EventPattern:
                source:
                    - aws.codepipeline
                detail-type:
                    - CodePipeline Pipeline Execution State Change
                    - CodePipeline Stage Execution State Change
                    - CodePipeline Action Execution State Change
            State: ENABLED
            Description: Triggered upon status change of CodePipeline
            Name: !Sub "${AppName}-status-pipeline-event"
            Targets:
                - Arn: !GetAtt
                      - StatusBadgeLambdaFunction
                      - Arn
                  Id: statusBadgeCloudWatchEvent
    StatusBadgeLambdaPermissionEventsRuleCloudWatchEvent2:
        Type: "AWS::Lambda::Permission"
        Properties:
            FunctionName: !GetAtt
                - StatusBadgeLambdaFunction
                - Arn
            Action: "lambda:InvokeFunction"
            Principal: events.amazonaws.com
            SourceArn: !GetAtt
                - StatusBadgeEventsRuleCloudWatchEvent2
                - Arn
    CommitIdBadgeEventsRuleCloudWatchEvent1:
        Type: "AWS::Events::Rule"
        Properties:
            EventPattern:
                source:
                    - aws.codepipeline
                detail-type:
                    - CodePipeline Pipeline Execution State Change
                    - CodePipeline Stage Execution State Change
                    - CodePipeline Action Execution State Change
            State: ENABLED
            Description: Triggered upon status change of CodePipeline
            Name: !Sub "${AppName}-commit-id-pipeline-event"
            Targets:
                - Arn: !GetAtt
                      - CommitIdBadgeLambdaFunction
                      - Arn
                  Id: commitIdBadgeCloudWatchEvent
    CommitIdBadgeLambdaPermissionEventsRuleCloudWatchEvent1:
        Type: "AWS::Lambda::Permission"
        Properties:
            FunctionName: !GetAtt
                - CommitIdBadgeLambdaFunction
                - Arn
            Action: "lambda:InvokeFunction"
            Principal: events.amazonaws.com
            SourceArn: !GetAtt
                - CommitIdBadgeEventsRuleCloudWatchEvent1
                - Arn

    # Images Bucket
    BuildBadgesImagesBucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
            BucketName: !Sub "${AppName}-images"
            OwnershipControls:
                Rules:
                    - ObjectOwnership: BucketOwnerEnforced
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
            WebsiteConfiguration:
                IndexDocument: index.html
            CorsConfiguration:
                CorsRules:
                    - AllowedHeaders:
                          - "*"
                      AllowedMethods:
                          - GET
                          - HEAD
                      AllowedOrigins:
                          - "https://github.com"
                          - "https://www.github.com"
                      MaxAge: 90
    BuildBadgesImagesBucketPolicy:
        Type: "AWS::S3::BucketPolicy"
        Properties:
            PolicyDocument:
                Id: !Sub "${AppName}-bucket-policy"
                Version: 2012-10-17
                Statement:
                    - Sid: PublicReadForGetBucketObjects
                      Effect: Allow
                      Principal: "*"
                      Action: "s3:GetObject"
                      Resource: !Sub "arn:aws:s3:::${BuildBadgesImagesBucket}/*"
            Bucket: !Ref BuildBadgesImagesBucket

    # Copy Lambda functions zip files to a bucked (LambdaZipsBucket)
    # which resides in the region of this stack
    CopyZips:
        Type: Custom::CopyZips
        Properties:
            ServiceToken: !GetAtt "CopyZipsFunction.Arn"
            DestBucket: !Ref "LambdaZipsBucket"
            SourceBucket: aws-build-badges-deployment-bucket
            Prefix: ""
            Objects:
                - dist_status_badges.zip
                - dist_commit_badges.zip
    CopyZipsRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Path: /
            Policies:
                - PolicyName: lambda-copier
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:GetObject
                            Resource:
                                - "arn:aws:s3:::aws-build-badges-deployment-bucket/*"
                          - Effect: Allow
                            Action:
                                - s3:PutObject
                                - s3:DeleteObject
                            Resource:
                                - !Sub "arn:aws:s3:::${LambdaZipsBucket}/*"

    CopyZipsFunction:
        Type: AWS::Lambda::Function
        Properties:
            Description: Copies objects from a source S3 bucket to a destination
            Handler: index.handler
            Runtime: python3.12
            Role: !GetAtt "CopyZipsRole.Arn"
            Timeout: 240
            Code:
                ZipFile: |
                    import json
                    import logging
                    import threading
                    import boto3
                    import cfnresponse
                    def copy_objects(source_bucket, dest_bucket, prefix, objects):
                        s3 = boto3.client('s3')
                        for o in objects:
                            key = prefix + o
                            copy_source = {
                                'Bucket': source_bucket,
                                'Key': key
                            }
                            print('copy_source: %s' % copy_source)
                            print('dest_bucket = %s'%dest_bucket)
                            print('key = %s' %key)
                            s3.copy_object(CopySource=copy_source, Bucket=dest_bucket,
                                    Key=key)
                    def delete_objects(bucket, prefix, objects):
                        s3 = boto3.client('s3')
                        objects = {'Objects': [{'Key': prefix + o} for o in objects]}
                        s3.delete_objects(Bucket=bucket, Delete=objects)
                    def timeout(event, context):
                        logging.error('Execution is about to time out, sending failure response to CloudFormation')
                        cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)
                    def handler(event, context):
                        # make sure we send a failure to CloudFormation if the function
                        # is going to timeout
                        timer = threading.Timer((context.get_remaining_time_in_millis()
                                    / 1000.00) - 0.5, timeout, args=[event, context])
                        timer.start()
                        print('Received event: %s' % json.dumps(event))
                        status = cfnresponse.SUCCESS
                        try:
                            source_bucket = event['ResourceProperties']['SourceBucket']
                            dest_bucket = event['ResourceProperties']['DestBucket']
                            prefix = event['ResourceProperties']['Prefix']
                            objects = event['ResourceProperties']['Objects']
                            if event['RequestType'] == 'Delete':
                                delete_objects(dest_bucket, prefix, objects)
                            else:
                                copy_objects(source_bucket, dest_bucket, prefix, objects)
                        except Exception as e:
                            logging.error('Exception: %s' % e, exc_info=True)
                            status = cfnresponse.FAILED
                        finally:
                            timer.cancel()
                            cfnresponse.send(event, context, status, {}, None)

    # No-op section removed

Outputs:
    LambdaZipsBucketName:
        Description: Contains the Lambda functions zip files
        Value: !Ref LambdaZipsBucket
    BuildBadgesImagesBucketName:
        Description: Name of the bucket containing generated images
        Value: !Ref BuildBadgesImagesBucket
